In [2]:
import os
import pandas as pd

dataset_name = "openalex"
base_dir = f"/home/martirano/data/{dataset_name}"
or_dir = os.path.join(base_dir, "raw/original_data")

In [3]:
filename = os.path.join(base_dir, 'snapshot_0', 'original_data/nodes/authors.csv')
df = pd.read_csv(filename, usecols=["id", "x_concepts"])
df.head()

            id                                         x_concepts
0  A5004271128  [{'id': 'https://openalex.org/C41008148', 'wik...
1  A5086198262  [{'id': 'https://openalex.org/C41008148', 'wik...
2  A5031185465  [{'id': 'https://openalex.org/C41008148', 'wik...
3  A5011125611  [{'id': 'https://openalex.org/C41008148', 'wik...
4  A5087188826  [{'id': 'https://openalex.org/C41008148', 'wik...

In [4]:
test = df.iloc[0]["x_concepts"]
test

"[{'id': 'https://openalex.org/C41008148', 'wikidata': 'https://www.wikidata.org/wiki/Q21198', 'display_name': 'Computer science', 'level': 0, 'score': 97.2}, {'id': 'https://openalex.org/C154945302', 'wikidata': 'https://www.wikidata.org/wiki/Q11660', 'display_name': 'Artificial intelligence', 'level': 1, 'score': 95.2}, {'id': 'https://openalex.org/C119857082', 'wikidata': 'https://www.wikidata.org/wiki/Q2539', 'display_name': 'Machine learning', 'level': 1, 'score': 77.9}, {'id': 'https://openalex.org/C33923547', 'wikidata': 'https://www.wikidata.org/wiki/Q395', 'display_name': 'Mathematics', 'level': 0, 'score': 70.3}, {'id': 'https://openalex.org/C138885662', 'wikidata': 'https://www.wikidata.org/wiki/Q5891', 'display_name': 'Philosophy', 'level': 0, 'score': 49.0}, {'id': 'https://openalex.org/C17744445', 'wikidata': 'https://www.wikidata.org/wiki/Q36442', 'display_name': 'Political science', 'level': 0, 'score': 45.5}, {'id': 'https://openalex.org/C105795698', 'wikidata': 'https://www.wikidata.org/wiki/Q12483', 'display_name': 'Statistics', 'level': 1, 'score': 45.5}, {'id': 'https://openalex.org/C199539241', 'wikidata': 'https://www.wikidata.org/wiki/Q7748', 'display_name': 'Law', 'level': 1, 'score': 44.8}, {'id': 'https://openalex.org/C50644808', 'wikidata': 'https://www.wikidata.org/wiki/Q192776', 'display_name': 'Artificial neural network', 'level': 2, 'score': 44.1}, {'id': 'https://openalex.org/C127413603', 'wikidata': 'https://www.wikidata.org/wiki/Q11023', 'display_name': 'Engineering', 'level': 0, 'score': 43.4}, {'id': 'https://openalex.org/C108583219', 'wikidata': 'https://www.wikidata.org/wiki/Q197536', 'display_name': 'Deep learning', 'level': 2, 'score': 39.3}, {'id': 'https://openalex.org/C121332964', 'wikidata': 'https://www.wikidata.org/wiki/Q413', 'display_name': 'Physics', 'level': 0, 'score': 39.3}, {'id': 'https://openalex.org/C199360897', 'wikidata': 'https://www.wikidata.org/wiki/Q9143', 'display_name': 'Programming language', 'level': 1, 'score': 37.2}, {'id': 'https://openalex.org/C15744967', 'wikidata': 'https://www.wikidata.org/wiki/Q9418', 'display_name': 'Psychology', 'level': 0, 'score': 35.2}, {'id': 'https://openalex.org/C37736160', 'wikidata': 'https://www.wikidata.org/wiki/Q1801315', 'display_name': 'Adversarial system', 'level': 2, 'score': 35.2}, {'id': 'https://openalex.org/C86803240', 'wikidata': 'https://www.wikidata.org/wiki/Q420', 'display_name': 'Biology', 'level': 0, 'score': 32.4}, {'id': 'https://openalex.org/C41895202', 'wikidata': 'https://www.wikidata.org/wiki/Q8162', 'display_name': 'Linguistics', 'level': 1, 'score': 31.7}, {'id': 'https://openalex.org/C162324750', 'wikidata': 'https://www.wikidata.org/wiki/Q8134', 'display_name': 'Economics', 'level': 0, 'score': 30.3}, {'id': 'https://openalex.org/C31972630', 'wikidata': 'https://www.wikidata.org/wiki/Q844240', 'display_name': 'Computer vision', 'level': 1, 'score': 28.3}, {'id': 'https://openalex.org/C62520636', 'wikidata': 'https://www.wikidata.org/wiki/Q944', 'display_name': 'Quantum mechanics', 'level': 1, 'score': 28.3}, {'id': 'https://openalex.org/C11413529', 'wikidata': 'https://www.wikidata.org/wiki/Q8366', 'display_name': 'Algorithm', 'level': 1, 'score': 25.5}, {'id': 'https://openalex.org/C111472728', 'wikidata': 'https://www.wikidata.org/wiki/Q9471', 'display_name': 'Epistemology', 'level': 1, 'score': 25.5}, {'id': 'https://openalex.org/C38652104', 'wikidata': 'https://www.wikidata.org/wiki/Q3510521', 'display_name': 'Computer security', 'level': 1, 'score': 22.8}, {'id': 'https://openalex.org/C111919701', 'wikidata': 'https://www.wikidata.org/wiki/Q9135', 'display_name': 'Operating system', 'level': 1, 'score': 22.1}, {'id': 'https://openalex.org/C180747234', 'wikidata': 'https://www.wikidata.org/wiki/Q23373', 'display_name': 'Cognitive psychology', 'level': 1, 'score': 21.4}]"

In [3]:
papers_all = pd.read_csv(os.path.join(or_dir, 'papers.csv'))
papers_all.head()

,id,doi,title,type,version,publication_date,publication_year,num_citations,num_citations_per_year
0,W2797148637,https://doi.org/10.2307/j.ctv10vm1qb,A Mathematical Theory of Evidence,book,NONE,2020-06-30,2020,5202,"[{'year': 2023, 'cited_by_count': 1}, {'year':..."
1,W2557283755,NaN,Deep Learning,book,NONE,2016-11-18,2016,3050,"[{'year': 2023, 'cited_by_count': 8}, {'year':..."
2,W1564897360,https://doi.org/10.1201/9781315136370,A Mathematical Introduction to Robotic Manipul...,book,NONE,2017-12-14,2017,2026,"[{'year': 2023, 'cited_by_count': 27}, {'year'..."
3,W1527571715,https://doi.org/10.7551/mitpress/11810.001.0001,Cybernetics or Control and Communication in th...,book,NONE,2019-01-01,2019,1810,"[{'year': 2023, 'cited_by_count': 12}, {'year'..."
4,W1537842733,https://doi.org/10.1201/9781420065619,Sliding Mode Control in Electro-Mechanical Sys...,book,NONE,2017-12-19,2017,1610,"[{'year': 2023, 'cited_by_count': 26}, {'year'..."

In [9]:
import torch

for snapshot in range(7):

    num_authors = torch.load(os.path.join(base_dir, f"snapshot_{snapshot}", "heterodata", "features", "author.pt")).shape[0]
    num_labels = torch.load(os.path.join(base_dir, f"snapshot_{snapshot}", "heterodata", "author_labels.pt")).shape[0]
    print(snapshot, num_authors, num_labels)

0 8600 8600
1 14059 14059
2 18891 18891
3 22893 22893
4 27218 27218
5 30565 30565
6 32713 32713

In [10]:
for snapshot in range(7):

    num_authors = pd.read_csv(os.path.join(base_dir, f"snapshot_{snapshot}", "original_data", "nodes", "author.csv")).shape[0]
    num_labels = pd.read_csv(os.path.join(base_dir, f"snapshot_{snapshot}", "original_data", "author_labels.csv")).shape[0]
    print(snapshot, num_authors, num_labels)

0 8600 8600
1 9040 9040
2 8293 8293
3 7177 7177
4 7874 7874
5 6395 6395
6 3699 3699